% function that checks the existence of file in the given directory

function [out] = check_file_existence(experiment_list, directory_list, sought_file)

found = 0;

%directory_list
for i=1:size(directory_list,2)
    file_list = dir(directory_list{i});
    dim_file_list = size(file_list);
    found = 0;
    for k=3:dim_file_list(1)    %start from 3 because the first entries are . and ..
        name_file = file_list(k).name;
        if (strcmp(name_file, sought_file))
            found =1;
            break;
        end
    end
end

if (found)
    out = true;
else   
    out = false;
    if (strcmp('archives_best_TEST.txt', sought_file))
        box_title = 'TEST data';
        box_message = 'Run test_eval.m to generate the file';
    end
    if (strcmp('archives_best.txt', sought_file))
        box_title = 'TRAINING data';
        box_message = 'Hint: check output directory (generated by experiment_new)';
    end
    warndlg({[sought_file ' not found']; [box_message]}, box_title)
    return
end
        
 